#!/bin/zsh


### Layout 
yabai -m config layout bsp

yabai -m config window_placement second_child



### Mouse
yabai -m config focus_follows_mouse autofocus


### Window Mods
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.5

yabai -m config window_topmost on
yabai -m config window_shadow float

### Automation with some Apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add title="Fantastical" manage=off
yabai -m rule --add title="FaceTime" manage=off

### Move the to the correct space
yabai -m rule --add app="^Google Chrome$" space=1
yabai -m rule --add app="^kitty$" space=2
yabai -m rule --add app="^Alacritty$" space=2
yabai -m rule --add app="^WezTerm$" space=2
yabai -m rule --add app="^Zotero$" space=4
# yabai -m rule --add app="^Obsidian$" space=2
yabai -m rule --add app="^Discord$" space=7
yabai -m rule --add app="^LINE$" space=7
# yabai -m rule --add app="Fantastical" space=5
yabai -m rule --add app="Brave Browser" space=6
yabai -m rule --add app="^Spotify$" space=10
yabai -m rule --add app="^GarageBand$" space=10
yabai -m rule --add app="^Mail$" space=11


### Intergration with Spacebar
SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:0:$SPACEBAR_HEIGHT




# if has-focus = off for finder, close it
#
#
#
#
#
# Float Mode
