require("toes.newremap")
require("toes.set")
require("toes.packer")
require("toes.color")
require("toes.telescope")
require("toes.remap")
require("toes.lsp")
require("toes.comp")
require("toes.comment")
-- require("toes.color-material")
